// Chart module guidelines — uses escaped backticks for code fences inside template literal

export const chartModule = {
  category: 'general',
  content: [
    '## Chart Module Guidelines',
    '',
    '### When to Use',
    'Bar, line, pie, doughnut, radar, scatter, bubble, or polar area charts for data comparison and trends.',
    '',
    '### Preferred Library',
    '**Chart.js** (loaded via CDN). Use D3.js only for advanced/custom charts.',
    '',
    '### Canvas Sizing (CRITICAL)',
    '- Wrap `<canvas>` in a `<div>` with explicit `height` and `position: relative`.',
    '- Set height ONLY on the wrapper div, NEVER on the canvas element itself.',
    '- Use `responsive: true, maintainAspectRatio: false` in Chart.js options.',
    '- For horizontal bar charts: wrapper height = `(number_of_bars × 40) + 80` pixels.',
    '- Load UMD build via `<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js">` — sets `window.Chart` global.',
    '',
    '### Custom Legends (ALWAYS)',
    'Always disable Chart.js default legend and build custom HTML:',
    '```js',
    'plugins: { legend: { display: false } }',
    '```',
    'Then add custom HTML legend ABOVE the chart:',
    '```html',
    '<div style="display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 8px; font-size: 12px; color: var(--color-text-secondary);">',
    '  <span style="display: flex; align-items: center; gap: 4px;"><span style="width: 10px; height: 10px; border-radius: 2px; background: #3266ad;"></span>Label 65%</span>',
    '</div>',
    '```',
    'Include value/percentage in each label for categorical data (pie, donut, single-series bar).',
    '',
    '### Template',
    '```html',
    '<div style="position: relative; width: 100%; height: 300px;">',
    '  <canvas id="myChart"></canvas>',
    '</div>',
    '<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>',
    '<script>',
    '  new Chart(document.getElementById("myChart"), {',
    '    type: "bar",',
    '    data: { labels: ["Q1","Q2","Q3","Q4"], datasets: [{ label: "Revenue", data: [12,19,8,15] }] },',
    '    options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }',
    '  });',
    '</script>',
    '```',
    '',
    '### Color Palette',
    'Use vibrant, distinguishable colors for datasets:',
    '- rgba(99, 102, 241, 0.7)  — Indigo',
    '- rgba(168, 85, 247, 0.7)  — Purple',
    '- rgba(236, 72, 153, 0.7)  — Pink',
    '- rgba(34, 197, 94, 0.7)   — Green',
    '- rgba(251, 146, 60, 0.7)  — Orange',
    '- rgba(14, 165, 233, 0.7)  — Sky',
    '',
    '### Number Formatting',
    '- Negative values: `-$5M` not `$-5M` — sign before currency symbol.',
    '- Use formatter: `(v) => (v < 0 ? "-" : "") + "$" + Math.abs(v) + "M"`',
    '',
    '### Best Practices',
    '- Canvas cannot resolve CSS variables. Use hardcoded hex or `getComputedStyle()` at runtime.',
    '- Multiple charts: use unique IDs (`myChart1`, `myChart2`). Each gets its own canvas+div.',
    '- For bubble/scatter charts: pad scale range ~10% beyond data to prevent clipping.',
    '- For ≤12 categories with all labels needed: set `scales.x.ticks: { autoSkip: false, maxRotation: 45 }`.',
    '- Include axis labels and units.',
    '- Add tooltips for data drill-down.',
    '- For comparison: use grouped/stacked bars. For trends: line charts with markers.',
    '- Use `sendPrompt("Break down Q4 by region")` for drill-down from metric cards.',
    '',
    '### Common Mistakes',
    '- Setting height on canvas instead of wrapper div (wrong dimensions).',
    '- Using Chart.js default legend (round dots, no values). Always build custom HTML.',
    '- Setting colors to hardcoded black/white (invisible in dark/light mode).',
    '- Forgetting responsive:true (chart does not resize).',
    '- Using var(--color-text) in Chart.js options — must use getComputedStyle() instead.',
  ].join('\n'),
  name: 'chart',
};
